<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;

class Project extends Model
{
    use HasFactory,SoftDeletes;

    protected $table = 'projects';
    protected $fillable = [
        'title',
        'description',
        'short_description',
        'cover_photo_path',
        'photo_paths',
        'interior_photo_paths',
        'exterior_photo_paths',
        'location',
        'construction_site',
        'count_housing',
        'architecture',
        'is_active',
        'sector_id',
        'room_types',
        'opportunities',
        'map_url',
        'order',
        'slug',
        'visit_count',
    ];

    protected $dates    = [ 'deleted_at'];

    protected $casts    = [
        'title'             => 'array',
        'short_description' => 'array',
        'description'       => 'array',
        'slug'              => 'array',
        'location'          => 'array',
        'room_types'        => 'array',
        'opportunities'     => 'array',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub


        self::creating(function ($model){
            $slugs  = [];
            foreach ($model->title as $key => $title){
                $slugs[$key] = Str::slug($title,'-');
            }
            $model->slug = $slugs;
        });

        self::created(function($model){
            $model->order       = $model->id;
            $model->visit_count = 0;
            $model->save();
        });

        self::updating(function ($model){
            $slugs  = [];
            foreach ($model->title as $key => $title){
                $slugs[$key] = Str::slug($title,'-');
            }
            $model->slug = $slugs;
        });

    }
}
