<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;

class Slider extends Model
{
    use HasFactory,SoftDeletes;

    protected $table = 'sliders';
    protected $fillable = [
        'title',
        'description',
        'redirect_url_name',
        'redirect_url',
        'project_id',
        'photo_path',
        'mobile_photo_path',
        'is_active',
        'order',
        'visit_count',
    ];

    protected $dates    = [ 'deleted_at'];

    protected $casts    = [
        'title'             => 'array',
        'description'       => 'array',
        'redirect_url'      => 'array',
        'redirect_url_name' => 'array',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        /*
        self::creating(function ($model){
            $slugs  = [];
            foreach ($model->name as $key => $name){
                $slugs[$key] = Str::slug($name,'-');
            }
            $model->slug = $slugs;
        });
        */
        self::created(function($model){
            $model->order       = $model->id;
            $model->visit_count = 0;
            $model->save();
        });
        /*
        self::updating(function ($model){
            $slugs  = [];
            foreach ($model->name as $key => $name){
                $slugs[$key] = Str::slug($name,'-');
            }
            $model->slug = $slugs;
        });
        */
    }
}
